service:
  name: "kratos_app"
http:
  server:
    # 使用 service.name 的值
    name: "${service.name}"
    # 使用环境变量 PORT 替换，若不存在，使用默认值 8080
    port: "${PORT:8080}"
    # 使用环境变量 TIMEOUT 替换，无默认值
    timeout: "$TIMEOUT"
